name: Update Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours at minute 0
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/activity-graph.yml'

concurrency:
  group: activity-graph-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Generate & Deploy Activity Graph
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Generate Activity Graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}
          options: radius=16&theme=dracula&area=true&order=5&hide_border=false&border_radius=12
          output_path: dist/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push activity-graph.svg to output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: activity-graph-output
          build_dir: dist
          commit_message: "chore(ci): update dynamic activity graph SVG [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
