name: Generate Arcade Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours at minute 0
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/arcade.yml'

concurrency:
  group: arcade-animation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    name: Generate & Deploy Pacman Graph
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Generate Pacman Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'pacman'

      - name: Push pacman-contribution-graph.svg to output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: pacman-output
          build_dir: dist
          commit_message: "chore(ci): update pacman contribution animation SVG [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
